/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akademik;

import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        siswa = new javax.swing.JMenuItem();
        matapelajaran = new javax.swing.JMenuItem();
        guru = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        nilai = new javax.swing.JMenu();
        form_nilai = new javax.swing.JMenuItem();
        nilai1 = new javax.swing.JMenu();
        form_nilai1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        siswa.setText("Input Siswa");
        siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaActionPerformed(evt);
            }
        });
        jMenu1.add(siswa);

        matapelajaran.setText("Input Mata Pelajaran");
        matapelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matapelajaranActionPerformed(evt);
            }
        });
        jMenu1.add(matapelajaran);

        guru.setText("Input Guru");
        guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guruActionPerformed(evt);
            }
        });
        jMenu1.add(guru);

        jMenuItem1.setText("Input Kelas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Input Pegawai");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        nilai.setText("Edit");

        form_nilai.setText("Input Nilai");
        form_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_nilaiActionPerformed(evt);
            }
        });
        nilai.add(form_nilai);

        jMenuBar1.add(nilai);

        nilai1.setText("About");
        nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilai1ActionPerformed(evt);
            }
        });

        form_nilai1.setText("Profil saya");
        form_nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_nilai1ActionPerformed(evt);
            }
        });
        nilai1.add(form_nilai1);

        jMenuBar1.add(nilai1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaActionPerformed
    form_siswa siswa = new form_siswa();
    desktop.add(siswa);
    siswa.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_siswaActionPerformed

    private void matapelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matapelajaranActionPerformed
    form_matapelajaran mapel = new form_matapelajaran();
    desktop.add(mapel);
    mapel.setVisible(true);  
// TODO add your handling code here:
    }//GEN-LAST:event_matapelajaranActionPerformed

    private void guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruActionPerformed
    form_guru guru = new form_guru();
    desktop.add(guru);
    guru.setVisible(true);    
// TODO add your handling code here:
    }//GEN-LAST:event_guruActionPerformed

    private void form_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_nilaiActionPerformed
    form_nilai nilai = new form_nilai();
    desktop.add(nilai);
    nilai.setVisible(false);
    JOptionPane.showMessageDialog(null, "Maaaf anda tidak dapat memperbaharui data nilai!");
    // TODO add your handling code here:
    }//GEN-LAST:event_form_nilaiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    form_kelas kelas = new form_kelas();
    desktop.add(kelas);
    kelas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    form_pegawai pegawai = new form_pegawai();
    desktop.add(pegawai);
    pegawai.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void form_nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_nilai1ActionPerformed
        // TODO add your handling code here:
        about saya = new about();
    desktop.add(saya);
    saya.setVisible(true);
   
    }//GEN-LAST:event_form_nilai1ActionPerformed

    private void nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilai1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem form_nilai;
    private javax.swing.JMenuItem form_nilai1;
    private javax.swing.JMenuItem guru;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem matapelajaran;
    private javax.swing.JMenu nilai;
    private javax.swing.JMenu nilai1;
    private javax.swing.JMenuItem siswa;
    // End of variables declaration//GEN-END:variables
}
